"use client";

import { create } from "zustand";
import { persist } from "zustand/middleware";

/* ─── Types ─── */

export type Priority = "low" | "medium" | "high" | "urgent";
export type Category = "class" | "assignment" | "personal" | "finance" | "community" | "admin";
export type Recurrence = "none" | "daily" | "weekly" | "monthly";

export interface ProdTask {
  id: string;
  title: string;
  notes: string;
  priority: Priority;
  category: Category;
  dueDate: string | null; // ISO
  completed: boolean;
  completedAt: string | null;
  progress: number; // 0..100
  recurrence: Recurrence;
  attachments: { name: string; url: string }[];
  order: number;
  createdAt: string;
  autoGenerated?: boolean;
  source?: string; // e.g. "admin:project", "class:abc123"
  xpReward: number;
}

export type EventKind = "class" | "deadline" | "meeting" | "event" | "payment" | "reward" | "competition";

export interface ProdEvent {
  id: string;
  title: string;
  description: string;
  start: string; // ISO
  end: string;   // ISO
  location: string;
  meetingUrl: string;
  kind: EventKind;
  recurrence: Recurrence;
  invitees: string[]; // emails
  rsvp: Record<string, "yes" | "no" | "maybe">;
  attended: string[]; // emails of attended
  createdAt: string;
}

export interface ProdReminder {
  id: string;
  refId: string; // task or event id
  refType: "task" | "event";
  label: string;
  fireAt: string; // ISO
  offsetMinutes: number;
  fired: boolean;
  deliverInApp: boolean;
  deliverPush: boolean;
  deliverEmail: boolean;
}

export interface ProdAlarm {
  id: string;
  label: string;
  fireAt: string; // ISO
  ringtone: "chime" | "beep" | "bell" | "digital";
  volume: number; // 0..1
  repeatDaily: boolean;
  active: boolean;
  snoozedUntil: string | null;
  fired: boolean;
}

export interface ProdStats {
  xp: number;
  streak: number;
  lastCompletionDate: string | null; // YYYY-MM-DD
  completionLog: { date: string; count: number }[]; // last 60 days
  performance: number; // 0..100
}

export type SuggestionSeed = {
  type: "project" | "class" | "fine" | "course" | "report";
  title: string;
  dueDate?: string;
  source: string;
};

interface State {
  tasks: ProdTask[];
  events: ProdEvent[];
  reminders: ProdReminder[];
  alarms: ProdAlarm[];
  stats: ProdStats;
  globalVolume: number;

  /* tasks */
  addTask: (t: Omit<ProdTask, "id" | "createdAt" | "order"> & Partial<Pick<ProdTask, "order">>) => string;
  updateTask: (id: string, patch: Partial<ProdTask>) => void;
  deleteTask: (id: string) => void;
  toggleTask: (id: string) => void;
  reorderTasks: (ids: string[]) => void;
  autoGenerateFromSeed: (seed: SuggestionSeed) => void;

  /* events */
  addEvent: (e: Omit<ProdEvent, "id" | "createdAt" | "rsvp" | "attended"> & Partial<Pick<ProdEvent, "rsvp" | "attended">>) => string;
  updateEvent: (id: string, patch: Partial<ProdEvent>) => void;
  deleteEvent: (id: string) => void;
  setRsvp: (eventId: string, userEmail: string, answer: "yes" | "no" | "maybe") => void;
  markAttended: (eventId: string, userEmail: string) => void;

  /* reminders */
  addReminder: (r: Omit<ProdReminder, "id" | "fired">) => string;
  deleteReminder: (id: string) => void;
  markReminderFired: (id: string) => void;

  /* alarms */
  addAlarm: (a: Omit<ProdAlarm, "id" | "fired" | "snoozedUntil" | "active"> & Partial<Pick<ProdAlarm, "active">>) => string;
  updateAlarm: (id: string, patch: Partial<ProdAlarm>) => void;
  deleteAlarm: (id: string) => void;
  snoozeAlarm: (id: string, minutes: number) => void;
  dismissAlarm: (id: string) => void;

  setGlobalVolume: (v: number) => void;
}

const uid = (p = "id") => `${p}_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 7)}`;

function todayYMD() {
  return new Date().toISOString().slice(0, 10);
}

function bumpStreak(stats: ProdStats): ProdStats {
  const today = todayYMD();
  if (stats.lastCompletionDate === today) return stats;
  const yesterday = new Date(Date.now() - 86400000).toISOString().slice(0, 10);
  const newStreak = stats.lastCompletionDate === yesterday ? stats.streak + 1 : 1;
  return { ...stats, streak: newStreak, lastCompletionDate: today };
}

function logCompletion(stats: ProdStats): ProdStats {
  const today = todayYMD();
  const existing = stats.completionLog.find((l) => l.date === today);
  const log = existing
    ? stats.completionLog.map((l) => (l.date === today ? { ...l, count: l.count + 1 } : l))
    : [...stats.completionLog, { date: today, count: 1 }];
  const trimmed = log.slice(-60);
  return { ...stats, completionLog: trimmed };
}

function recalcPerformance(stats: ProdStats): number {
  const last7 = stats.completionLog.slice(-7).reduce((s, l) => s + l.count, 0);
  // 14 completions in 7 days = 100%
  return Math.min(100, Math.round((last7 / 14) * 100));
}

export const useProductivityStore = create<State>()(
  persist(
    (set) => ({
      tasks: [],
      events: [],
      reminders: [],
      alarms: [],
      stats: { xp: 0, streak: 0, lastCompletionDate: null, completionLog: [], performance: 0 },
      globalVolume: 0.7,

      addTask: (t) => {
        const id = uid("task");
        set((s) => ({
          tasks: [
            ...s.tasks,
            {
              id,
              createdAt: new Date().toISOString(),
              order: s.tasks.length,
              ...t,
            } as ProdTask,
          ],
        }));
        return id;
      },
      updateTask: (id, patch) =>
        set((s) => ({ tasks: s.tasks.map((t) => (t.id === id ? { ...t, ...patch } : t)) })),
      deleteTask: (id) =>
        set((s) => ({
          tasks: s.tasks.filter((t) => t.id !== id),
          reminders: s.reminders.filter((r) => !(r.refType === "task" && r.refId === id)),
        })),
      toggleTask: (id) =>
        set((s) => {
          const t = s.tasks.find((x) => x.id === id);
          if (!t) return {};
          const now = new Date().toISOString();
          const completing = !t.completed;
          const updatedTasks = s.tasks.map((x) =>
            x.id === id
              ? { ...x, completed: completing, completedAt: completing ? now : null, progress: completing ? 100 : x.progress }
              : x
          );
          if (!completing) return { tasks: updatedTasks };
          let stats = bumpStreak(s.stats);
          stats = logCompletion(stats);
          stats = { ...stats, xp: stats.xp + (t.xpReward || 10) };
          stats = { ...stats, performance: recalcPerformance(stats) };
          // If recurring, spawn the next instance
          let next = updatedTasks;
          if (t.recurrence !== "none" && t.dueDate) {
            const nextDue = new Date(t.dueDate);
            if (t.recurrence === "daily") nextDue.setDate(nextDue.getDate() + 1);
            if (t.recurrence === "weekly") nextDue.setDate(nextDue.getDate() + 7);
            if (t.recurrence === "monthly") nextDue.setMonth(nextDue.getMonth() + 1);
            next = [
              ...updatedTasks,
              {
                ...t,
                id: uid("task"),
                completed: false,
                completedAt: null,
                progress: 0,
                dueDate: nextDue.toISOString(),
                createdAt: now,
                order: updatedTasks.length,
              },
            ];
          }
          return { tasks: next, stats };
        }),
      reorderTasks: (ids) =>
        set((s) => {
          const map = new Map(s.tasks.map((t) => [t.id, t]));
          const reordered = ids.map((id, i) => ({ ...(map.get(id)!), order: i })).filter(Boolean);
          const untouched = s.tasks.filter((t) => !ids.includes(t.id));
          return { tasks: [...reordered, ...untouched] };
        }),
      autoGenerateFromSeed: (seed) =>
        set((s) => {
          const exists = s.tasks.some((t) => t.source === seed.source);
          if (exists) return {};
          const id = uid("task");
          const task: ProdTask = {
            id,
            title: seed.title,
            notes: "",
            priority: seed.type === "fine" ? "urgent" : seed.type === "project" ? "high" : "medium",
            category:
              seed.type === "class" ? "class" :
              seed.type === "report" || seed.type === "project" ? "assignment" :
              seed.type === "fine" ? "finance" :
              seed.type === "course" ? "class" : "personal",
            dueDate: seed.dueDate || null,
            completed: false,
            completedAt: null,
            progress: 0,
            recurrence: "none",
            attachments: [],
            order: s.tasks.length,
            createdAt: new Date().toISOString(),
            autoGenerated: true,
            source: seed.source,
            xpReward: seed.type === "fine" ? 0 : 20,
          };
          return { tasks: [...s.tasks, task] };
        }),

      addEvent: (e) => {
        const id = uid("evt");
        set((s) => ({
          events: [
            ...s.events,
            { id, createdAt: new Date().toISOString(), rsvp: {}, attended: [], ...e } as ProdEvent,
          ],
        }));
        return id;
      },
      updateEvent: (id, patch) =>
        set((s) => ({ events: s.events.map((e) => (e.id === id ? { ...e, ...patch } : e)) })),
      deleteEvent: (id) =>
        set((s) => ({
          events: s.events.filter((e) => e.id !== id),
          reminders: s.reminders.filter((r) => !(r.refType === "event" && r.refId === id)),
        })),
      setRsvp: (eventId, email, answer) =>
        set((s) => ({
          events: s.events.map((e) =>
            e.id === eventId ? { ...e, rsvp: { ...e.rsvp, [email]: answer } } : e
          ),
        })),
      markAttended: (eventId, email) =>
        set((s) => ({
          events: s.events.map((e) =>
            e.id === eventId && !e.attended.includes(email)
              ? { ...e, attended: [...e.attended, email] }
              : e
          ),
        })),

      addReminder: (r) => {
        const id = uid("rem");
        set((s) => ({ reminders: [...s.reminders, { id, fired: false, ...r }] }));
        return id;
      },
      deleteReminder: (id) => set((s) => ({ reminders: s.reminders.filter((r) => r.id !== id) })),
      markReminderFired: (id) =>
        set((s) => ({ reminders: s.reminders.map((r) => (r.id === id ? { ...r, fired: true } : r)) })),

      addAlarm: (a) => {
        const id = uid("alm");
        set((s) => ({
          alarms: [...s.alarms, { id, fired: false, snoozedUntil: null, active: true, ...a }],
        }));
        return id;
      },
      updateAlarm: (id, patch) =>
        set((s) => ({ alarms: s.alarms.map((a) => (a.id === id ? { ...a, ...patch } : a)) })),
      deleteAlarm: (id) => set((s) => ({ alarms: s.alarms.filter((a) => a.id !== id) })),
      snoozeAlarm: (id, minutes) =>
        set((s) => ({
          alarms: s.alarms.map((a) =>
            a.id === id
              ? { ...a, snoozedUntil: new Date(Date.now() + minutes * 60000).toISOString(), fired: false }
              : a
          ),
        })),
      dismissAlarm: (id) =>
        set((s) => ({
          alarms: s.alarms.map((a) =>
            a.id === id ? { ...a, fired: true, snoozedUntil: null, active: a.repeatDaily ? true : false } : a
          ),
        })),
      setGlobalVolume: (v) => set({ globalVolume: Math.max(0, Math.min(1, v)) }),
    }),
    { name: "cios-productivity-v1" }
  )
);
