"use client";

/* Study Buddy v2 — offline library (Phase 3).
 *
 * Saves session bundles (generated by getOfflinePack on the server) to
 * localStorage so users can review flashcards, podcast scripts, explain text,
 * and story text without a network connection.
 *
 * Storage model:
 *   cios-sb-offline-index : array of { sessionId, topic, savedAt, bytes }
 *   cios-sb-offline-<id>  : the full bundle JSON
 *
 * Capacity: localStorage caps at ~5MB per origin. We keep only 3 most recent
 * bundles (roadmap ship criterion) and evict oldest when adding a new one.
 *
 * At launch we may switch to IndexedDB for larger bundles (ElevenLabs audio
 * blobs can push past 5MB) — the interface here stays the same.
 */

const INDEX_KEY = "cios-sb-offline-index";
const BUNDLE_PREFIX = "cios-sb-offline-";
const MAX_BUNDLES = 3;

export interface OfflineIndexEntry {
  sessionId: string;
  topic: string;
  savedAt: string;
  bytes: number;
}

function readIndex(): OfflineIndexEntry[] {
  try {
    const raw = localStorage.getItem(INDEX_KEY);
    if (!raw) return [];
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function writeIndex(entries: OfflineIndexEntry[]): void {
  try { localStorage.setItem(INDEX_KEY, JSON.stringify(entries)); } catch { /* quota */ }
}

export function listOfflineBundles(): OfflineIndexEntry[] {
  if (typeof window === "undefined") return [];
  return readIndex().sort((a, b) => b.savedAt.localeCompare(a.savedAt));
}

export function loadOfflineBundle<T = unknown>(sessionId: string): T | null {
  if (typeof window === "undefined") return null;
  try {
    const raw = localStorage.getItem(BUNDLE_PREFIX + sessionId);
    return raw ? (JSON.parse(raw) as T) : null;
  } catch {
    return null;
  }
}

export function saveOfflineBundle(sessionId: string, topic: string, bundle: unknown): { ok: true } | { ok: false; error: string } {
  if (typeof window === "undefined") return { ok: false, error: "server" };
  const serialized = JSON.stringify(bundle);
  const bytes = new Blob([serialized]).size;

  // Evict oldest if we're at capacity and this session is new
  let idx = readIndex();
  const existing = idx.findIndex((e) => e.sessionId === sessionId);
  if (existing === -1 && idx.length >= MAX_BUNDLES) {
    idx.sort((a, b) => a.savedAt.localeCompare(b.savedAt));
    const evicted = idx.shift();
    if (evicted) localStorage.removeItem(BUNDLE_PREFIX + evicted.sessionId);
  }

  try {
    localStorage.setItem(BUNDLE_PREFIX + sessionId, serialized);
  } catch {
    return { ok: false, error: "Storage full — delete an older pack and try again" };
  }

  idx = idx.filter((e) => e.sessionId !== sessionId);
  idx.push({ sessionId, topic, savedAt: new Date().toISOString(), bytes });
  writeIndex(idx);
  return { ok: true };
}

export function deleteOfflineBundle(sessionId: string): void {
  if (typeof window === "undefined") return;
  try {
    localStorage.removeItem(BUNDLE_PREFIX + sessionId);
    writeIndex(readIndex().filter((e) => e.sessionId !== sessionId));
  } catch { /* ignore */ }
}

/** Tiny helper to format bytes for the offline library UI. */
export function formatBytes(n: number): string {
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${(n / 1024).toFixed(1)} KB`;
  return `${(n / (1024 * 1024)).toFixed(2)} MB`;
}
