import { NextResponse } from "next/server";
import { getCurrentDbUser } from "@/lib/db";
import { callLLM, logAiUsage } from "@/lib/ai-client";

export const runtime = "nodejs";

export async function POST(req: Request) {
  const me = await getCurrentDbUser();
  if (!me) return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  if (me.role !== "instructor" && me.role !== "admin" && me.role !== "super_admin") {
    return NextResponse.json({ error: "instructor privileges required" }, { status: 403 });
  }
  const body = await req.json();
  const text: string = (body?.text || "").toString().slice(0, 10000);
  if (!text.trim()) return NextResponse.json({ error: "empty text" }, { status: 400 });

  try {
    const r = await callLLM(
      `Analyze the following student submission for two things:\n1) Likelihood (0-100%) that it was generated by AI (ChatGPT, Claude, Gemini, etc.). Consider stylistic uniformity, lack of personal voice, generic phrasing, and overuse of transitions.\n2) Likelihood (0-100%) of plagiarism — repetitive stock phrases, textbook-style blocks, pattern-matched content.\n\nReturn STRICT JSON in this exact shape and nothing else:\n{"ai_likelihood": <number 0-100>, "plagiarism_likelihood": <number 0-100>, "verdict": "<one short sentence>", "signals": ["<bullet>", "<bullet>", "<bullet>"]}\n\nSUBMISSION:\n"""${text}"""`,
      { maxTokens: 500, temperature: 0 }
    );
    let parsed: unknown = null;
    try {
      const match = r.text.match(/\{[\s\S]*\}/);
      parsed = match ? JSON.parse(match[0]) : JSON.parse(r.text);
    } catch {
      parsed = { ai_likelihood: null, plagiarism_likelihood: null, verdict: r.text.slice(0, 200), signals: [] };
    }
    await logAiUsage(me.id, "detect", r.provider);
    return NextResponse.json({ result: parsed, provider: r.provider, model: r.model });
  } catch (e) {
    return NextResponse.json({ error: e instanceof Error ? e.message : String(e) }, { status: 500 });
  }
}
